giving-item-stacks-amount: 9
take-floor-drop: false
food-level-decreases: false
ticks-between-item-drop: 1200
items:
  - ACACIA_BOAT
  - ACACIA_CHEST_BOAT
  - ACACIA_DOOR
  - ACACIA_FENCE
  - ACACIA_FENCE_GATE
  - ACACIA_LEAVES
  - ACACIA_LOG
  - ACACIA_PLANKS
  - ACACIA_PRESSURE_PLATE
  - ACACIA_SLAB
  - ACACIA_STAIRS
  - ACACIA_TRAPDOOR
  - ACACIA_WOOD
  - ACTIVATOR_RAIL
  - ALLAY_SPAWN_EGG
  - AMETHYST_BLOCK
  - AMETHYST_CLUSTER
  - AMETHYST_SHARD
  - ANCIENT_DEBRIS
  - ANDESITE
  - ANDESITE_SLAB
  - ANDESITE_STAIRS
  - ANDESITE_WALL
  - ANVIL
#  - APPLE
  - ARMOR_STAND
  - ARROW
  - AXOLOTL_BUCKET
  - AZURE_BLUET
  - BAKED_POTATO
  - BAMBOO
  - BARREL
  - BASALT
  - BAT_SPAWN_EGG
  - BEACON
  - BEE_NEST
  - BEE_SPAWN_EGG
  - BEEF
  - BEEHIVE
  - BEETROOT
  - BEETROOT_SOUP
  - BEETROOTS
  - BELL
  - BIRCH_BOAT
  - BIRCH_CHEST_BOAT
  - BIRCH_DOOR
  - BIRCH_FENCE
  - BIRCH_FENCE_GATE
  - BIRCH_LEAVES
  - BIRCH_LOG
  - BIRCH_PLANKS
  - BIRCH_PRESSURE_PLATE
  - BIRCH_SLAB
  - BIRCH_STAIRS
  - BIRCH_TRAPDOOR
  - BIRCH_WOOD
  - BLACK_BED
  - BLACK_CONCRETE
  - BLACK_CONCRETE_POWDE
  - BLACK_GLAZED_TERRACOTTA
  - BLACK_STAINED_GLASS
  - BLACK_TERRACOTTA
  - BLACK_WOOL
  - BLACKSTONE
  - BLACKSTONE_SLAB
  - BLACKSTONE_STAIRS
  - BLACKSTONE_WALL
  - BLAST_FURNACE
  - BLAZE_POWDER
  - BLAZE_ROD
  - BLAZE_SPAWN_EGG
  - BLUE_BED
  - BLUE_CONCRETE
  - BLUE_CONCRETE_POWDER
  - BLUE_GLAZED_TERRACOTTA
  - BLUE_ICE
  - BLUE_STAINED_GLASS
  - BLUE_TERRACOTTA
  - BLUE_WOOL
  - BONE
  - BONE_BLOCK
  - BOOK
  - BOOKSHELF
  - BOW
  - BRAIN_CORAL_BLOCK
#  - BREAD
  - BREWING_STAND
  - BRICK
  - BRICK_SLAB
  - BRICK_STAIRS
  - BRICK_WALL
  - BROWN_BED
  - BROWN_CONCRETE
  - BROWN_CONCRETE_POWDER
  - BROWN_GLAZED_TERRACOTTA
  - BROWN_MUSHROOM_BLOCK
  - BROWN_STAINED_GLASS
  - BROWN_TERRACOTTA
  - BROWN_WOOL
  - BUBBLE_COLUMN
  - BUBBLE_CORAL_BLOCK
  - BUCKET
  - BUDDING_AMETHYST
  - CACTUS
  - CALCITE
  - CAMPFIRE
#  - CARROT
#  - CARROTS
  - CARTOGRAPHY_TABLE
  - CARVED_PUMPKIN
  - CAT_SPAWN_EGG
  - CAULDRON
  - CAVE_SPIDER_SPAWN_EGG
  - CHAIN
  - CHAINMAIL_BOOTS
  - CHAINMAIL_CHESTPLATE
  - CHAINMAIL_HELMET
  - CHAINMAIL_LEGGINGS
  - CHARCOAL
  - CHEST
  - CHICKEN
  - CHICKEN_SPAWN_EGG
  - CHIPPED_ANVIL
  - CHISELED_DEEPSLATE
  - CHISELED_NETHER_BRICKS
  - CHISELED_POLISHED_BLACKSTONE
  - CHISELED_QUARTZ_BLOCK
  - CHISELED_RED_SANDSTONE
  - CHISELED_SANDSTONE
  - CHISELED_STONE_BRICKS
  - CHORUS_FRUIT
  - CHORUS_PLANT
  - CLAY
  - CLOCK
  - COAL
  - COAL_BLOCK
  - COARSE_DIRT
  - COBBLED_DEEPSLATE
  - COBBLED_DEEPSLATE_SLAB
  - COBBLED_DEEPSLATE_STAIRS
  - COBBLED_DEEPSLATE_WALL
  - COBBLESTONE
  - COBBLESTONE_SLAB
  - COBBLESTONE_STAIRS
  - COBBLESTONE_WALL
  - COBWEB
  - COD
  - COD_BUCKET
  - COD_SPAWN_EGG
  - COMPOSTER
  - CONDUIT
#  - COOKED_BEEF
#  - COOKED_CHICKEN
#  - COOKED_COD
#  - COOKED_MUTTON
#  - COOKED_RABBIT
#  - COOKED_SALMON
#  - COOKIE
  - COPPER_BLOCK
  - COPPER_ORE
  - COW_SPAWN_EGG
  - CRACKED_DEEPSLATE_BRICKS
  - CRACKED_DEEPSLATE_TILES
  - CRACKED_NETHER_BRICKS
  - CRACKED_POLISHED_BLACKSTONE_BRICKS
  - CRACKED_STONE_BRICKS
  - CRAFTING_TABLE
  - CREEPER_SPAWN_EGG
  - CRIMSON_DOOR
  - CRIMSON_FENCE
  - CRIMSON_FENCE_GATE
  - CRIMSON_FUNGUS
  - CRIMSON_HYPHAE
  - CRIMSON_NYLIUM
  - CRIMSON_PLANKS
  - CRIMSON_PRESSURE_PLATE
  - CRIMSON_ROOTS
  - CRIMSON_SLAB
  - CRIMSON_STAIRS
  - CRIMSON_STEM
  - CRIMSON_TRAPDOOR
  - CROSSBOW
  - CRYING_OBSIDIAN
  - CUT_COPPER
  - CUT_COPPER_SLAB
  - CUT_COPPER_STAIRS
  - CUT_RED_SANDSTONE
  - CUT_RED_SANDSTONE_SLAB
  - CUT_SANDSTONE
  - CUT_SANDSTONE_SLAB
  - CYAN_BED
  - CYAN_CONCRETE
  - CYAN_CONCRETE_POWDER
  - C- YAN_GLAZED_TERRACOTTA
  - CYAN_STAINED_GLASS
  - CYAN_TERRACOTTA
  - CYAN_WOOL
  - DAMAGED_ANVIL
  - DANDELION
  - DARK_OAK_BOAT
  - DARK_OAK_CHEST_BOAT
  - DARK_OAK_DOOR
  - DARK_OAK_FENCE
  - DARK_OAK_FENCE_GATE
  - DARK_OAK_LEAVES
  - DARK_OAK_LOG
  - DARK_OAK_PLANKS
  - DARK_OAK_PRESSURE_PLATE
  - DARK_OAK_SLAB-
  - DARK_OAK_STAIRS
  - DARK_OAK_TRAPDOOR
  - DARK_OAK_WOOD
  - DARK_PRISMARINE
  - DARK_PRISMARINE_SLAB
  - DARK_PRISMARINE_STAIRS
  - DAYLIGHT_DETECTOR
  - DEAD_BRAIN_CORAL_BLOCK
  - DEAD_BUBBLE_CORAL_BLOCK
  - DEAD_BUSH
  - DEAD_FIRE_CORAL_BLOCK
  - DEAD_HORN_CORAL_BLOCK
  - DEAD_TUBE_CORAL_BLOCK
  - DEEPSLATE
  - DEEPSLATE_BRICK_SLAB
  - DEEPSLATE_BRICK_STAIRS
  - DEEPSLATE_BRICK_WALL
  - DEEPSLATE_BRICKS
  - DEEPSLATE_COAL_ORE
  - DEEPSLATE_COPPER_ORE
  - DEEPSLATE_DIAMOND_ORE
  - DEEPSLATE_EMERALD_ORE
  - DEEPSLATE_GOLD_ORE
  - DEEPSLATE_IRON_ORE
  - DEEPSLATE_LAPIS_ORE
  - DEEPSLATE_REDSTONE_ORE
  - DEEPSLATE_TILE_SLAB
  - DEEPSLATE_TILE_STAIRS
  - DEEPSLATE_TILE_WALL
  - DEEPSLATE_TILES
  - DETECTOR_RAIL
  - DIAMOND
  - DIAMOND_AXE
  - DIAMOND_BLOCK
  - DIAMOND_BOOTS
  - DIAMOND_CHESTPLATE
  - DIAMOND_HELMET
  - DIAMOND_HORSE_ARMOR
  - DIAMOND_LEGGINGS
  - DIAMOND_ORE
  - DIAMOND_PICKAXE
  - DIAMOND_SHOVEL
  - DIAMOND_SWORD
  - DIORITE
  - DIORITE_SLAB
  - DIORITE_STAIRS
  - DIORITE_WALL
  - DIRT
  - DIRT_PATH
  - DISPENSER
  - DOLPHIN_SPAWN_EGG
  - - DONKEY_SPAWN_EGG
  - DRAGON_BREATH
  - DRAGON_EGG
  - DRIED_KELP
  - DRIED_KELP_BLOCK
  - DRIPSTONE_BLOCK
  - DROPPER
  - DROWNED_SPAWN_EGG
  - ECHO_SHARD
  - EGG
  - ELDER_GUARDIAN_SPAWN_EGG
  - ELYTRA
  - EMERALD
  - EMERALD_BLOCK
  - EMERALD_ORE
  - ENCHANTED_BOOK
  - ENCHANTED_GOLDEN_APPLE
  - ENCHANTING_TABLE
  - END_CRYSTAL
  - END_GATEWAY
  - END_PORTAL
  - END_PORTAL_FRAME
  - END_ROD
  - END_STONE
  - END_STONE_BRICK_SLAB
  - END_STONE_BRICK_STAIRS
  - END_STONE_BRICK_WALL
  - END_STONE_BRICKS
  - ENDER_CHEST
  - E- NDER_EYE
  - ENDER_PEARL
  - ENDERMAN_SPAWN_EGG
  - ENDERMITE_SPAWN_EGG
  - EVOKER_SPAWN_EGG
  - EXPERIENCE_BOTTLE
  - EXPOSED_COPPER
  - EXPOSED_CUT_COPPER
  - EXPOSED_CUT_COPPER_SLAB
  - EXPOSED_CUT_COPPER_STAIRS
  - FARMLAND
  - FEATHER
  - FERMENTED_SPIDER_EYE
  - FERN
  - FIRE_CHARGE
  - FIRE_CORAL_BLOCK
  - FIREWORK_ROCKET
  - FIREWORK_STAR
  - FISHING_ROD
  - FLETCHING_TABLE
  - FLINT
  - FLINT_AND_STEEL
  - FOX_SPAWN_EGG
  - FROG_SPAWN_EGG
  - FROGSPAWN
  - FROSTED_ICE
  - FURNACE
  - GHAST_SPAWN_EGG
  - GHAST_TEAR
  - GILDED_BLACKSTONE
  - GLASS
  - GLASS_BOTTLE
  - GLISTERING_MELON_SLICE
#  - GLOW_BERRIES
  - GLOW_INK_SAC
  - GLOW_LICHEN
  - GLOW_SQUID_SPAWN_EGG
  - GLOWSTONE
  - GLOWSTONE_DUST
  - GOAT_HORN
  - GOAT_SPAWN_EGG
  - GOLD_BLOCK
  - GOLD_INGOT
  - GOLD_NUGGET
  - GOLD_ORE
  - GOLDEN_APPLE
  - GOLDEN_AXE
  - GOLDEN_BOOTS
#  - GOLDEN_CARROT
  - GOLDEN_CHESTPLATE
  - GOLDEN_HELMET
  - GOLDEN_HORSE_ARMOR
  - GOLDEN_LEGGINGS
  - GOLDEN_PICKAXE
  - GOLDEN_SHOVEL
  - GOLDEN_SWORD
  - GRANITE
  - GRANITE_SLAB
  - GRANITE_STAIRS
  - GRANITE_WALL
  - GRASS_BLOCK
  - GRAVEL
  - GRAY_BED
  - GRAY_CONCRETE
  - GRAY_CONCRETE_POWDER
  - GRAY_GLAZED_TERRACOTTA
  - GRAY_STAINED_GLASS
  - GRAY_TERRACOTTA
  - GRAY_WOOL
  - GREEN_BED
  - GREEN_CONCRETE
  - GREEN_CONCRETE_POWDER
  - GREEN_GLAZED_TERRACOTTA
  - GREEN_STAINED_GLASS
  - GREEN_TERRACOTTA
  - GREEN_WOOL
  - GRINDSTONE
  - GUARDIAN_SPAWN_EGG
  - GUNPOWDER
  - HANGING_ROOTS
  - HAY_BLOCK
  - HEART_OF_THE_SEA
  - HEAVY_WEIGHTED_PRESSURE_PLATE
  - HOGLIN_SPAWN_EGG
  - HONEY_BLOCK
  - HONEY_BOTTLE
  - HONEYCOMB
  - HONEYCOMB_BLOCK
  - HOPPER
  - HORN_CORAL
  - HORN_CORAL_BLOCK
  - HORN_CORAL_FAN
  - HORN_CORAL_WALL_FAN
  - HORSE_SPAWN_EGG
  - HUSK_SPAWN_EGG
  - ICE
  - INFESTED_CHISELED_STONE_BRICKS
  - INFESTED_COBBLESTONE
  - INFESTED_CRACKED_STONE_BRICKS
  - INFESTED_DEEPSLATE
  - INFESTED_MOSSY_STONE_BRICKS
  - INFESTED_STONE
  - INFESTED_STONE_BRICKS
  - IRON_AXE
  - IRON_BARS
  - IRON_BLOCK
  - IRON_BOOTS
  - IRON_CHESTPLATE
  - IRON_DOOR
  - IRON_HELMET
  - IRON_HORSE_ARMOR
  - IRON_INGOT
  - IRON_LEGGINGS
  - IRON_NUGGET
  - IRON_ORE
  - IRON_PICKAXE
  - IRON_SHOVEL
  - IRON_SWORD
  - IRON_TRAPDOOR
  - JACK_O_LANTERN
  - JIGSAW
  - JUKEBOX
  - JUNGLE_BOAT
  - JUNGLE_CHEST_BOAT
  - JUNGLE_DOOR
  - JUNGLE_FENCE
  - JUNGLE_FENCE_GATE
  - JUNGLE_LEAVES
  - JUNGLE_LOG
  - JUNGLE_PLANKS
  - JUNGLE_PRESSURE_PLATE
  - JUNGLE_SLAB
  - JUNGLE_STAIRS
  - JUNGLE_TRAPDOOR
  - JUNGLE_WOOD
  - KELP_PLANT
  - KNOWLEDGE_BOOK
  - LADDER
  - LANTERN
  - LAPIS_BLOCK
  - LAPIS_LAZULI
  - LAPIS_ORE
  - LARGE_AMETHYST_BUD
  - LARGE_FERN
  - LAVA_BUCKET
  - LAVA_CAULDRON
  - LEAD
  - LEATHER
  - LEATHER_BOOTS
  - LEATHER_CHESTPLATE
  - LEATHER_HELMET
  - LEATHER_HORSE_ARMOR
  - LEATHER_LEGGINGS
  - LECTERN
  - LEVER
  - LIGHT
  - LIGHT_BLUE_BED
  - LIGHT_BLUE_CONCRETE
  - LIGHT_BLUE_CONCRETE_POWDER
  - LIGHT_BLUE_GLAZED_TERRACOTTA
  - LIGHT_BLUE_STAINED_GLASS
  - LIGHT_BLUE_TERRACOTTA
  - LIGHT_BLUE_WOOL
  - LIGHT_GRAY_BED
  - LIGHT_GRAY_CONCRETE
  - LIGHT_GRAY_CONCRETE_POWDER
  - LIGHT_GRAY_GLAZED_TERRACOTTA
  - LIGHT_GRAY_STAINED_GLASS
  - LIGHT_GRAY_TERRACOTTA
  - LIGHT_GRAY_WOOL
  - LIGHT_WEIGHTED_PRESSURE_PLATE
  - LIGHTNING_ROD
  - LIME_BED
  - LIME_CONCRETE
  - LIME_CONCRETE_POWDER
  - LIME_GLAZED_TERRACOTTA
  - LIME_STAINED_GLASS
  - LIME_TERRACOTTA
  - LIME_WOOL
  - LINGERING_POTION
  - LLAMA_SPAWN_EGG
  - LODESTONE
  - LOOM
  - MAGENTA_BED
  - MAGENTA_CONCRETE
  - MAGENTA_CONCRETE_POWDER
  - MAGENTA_GLAZED_TERRACOTTA
  - MAGENTA_STAINED_GLASS
  - MAGENTA_TERRACOTTA
  - MAGENTA_WOOL
  - MAGMA_BLOCK
  - MAGMA_CREAM
  - MAGMA_CUBE_SPAWN_EGG
  - MANGROVE_BOAT
  - MANGROVE_CHEST_BOAT
  - MANGROVE_DOOR
  - MANGROVE_FENCE
  - MANGROVE_FENCE_GATE
  - MANGROVE_LEAVES
  - MANGROVE_LOG
  - MANGROVE_PLANKS
  - MANGROVE_PRESSURE_PLATE
  - MANGROVE_ROOTS
  - MANGROVE_SLAB
  - MANGROVE_STAIRS
  - MANGROVE_TRAPDOOR
  - MANGROVE_WOOD
  - MAP
  - MEDIUM_AMETHYST_BUD
  - MELON
  - MELON_SLICE
  - MELON_STEM
  - MILK_BUCKET
  - MINECART
  - MOOSHROOM_SPAWN_EGG
  - MOSS_BLOCK
  - MOSSY_COBBLESTONE
  - MOSSY_COBBLESTONE_SLAB
  - MOSSY_COBBLESTONE_STAIRS
  - MOSSY_COBBLESTONE_WALL
  - MOSSY_STONE_BRICK_SLAB
  - MOSSY_STONE_BRICK_STAIRS
  - MOSSY_STONE_BRICK_WALL
  - MOSSY_STONE_BRICKS
  - MOVING_PISTON
  - MUD
  - MUD_BRICK_SLAB
  - MUD_BRICK_STAIRS
  - MUD_BRICK_WALL
  - MUD_BRICKS
  - MUDDY_MANGROVE_ROOTS
  - MULE_SPAWN_EGG
  - MUSHROOM_STEM
  - MUSHROOM_STEW
  - MUTTON
  - MYCELIUM
  - NAME_TAG
  - NAUTILUS_SHELL
  - NETHER_BRICK
  - NETHER_BRICK_FENCE
  - NETHER_BRICK_SLAB
  - NETHER_BRICK_STAIRS
  - NETHER_BRICK_WALL
  - NETHER_BRICKS
  - NETHER_GOLD_ORE
  - NETHER_PORTAL
  - NETHER_QUARTZ_ORE
  - NETHER_SPROUTS
  - NETHER_STAR
  - NETHER_WART
  - NETHER_WART_BLOCK
  - NETHERITE_AXE
  - NETHERITE_BLOCK
  - NETHERITE_BOOTS
  - NETHERITE_CHESTPLATE
  - NETHERITE_HELMET
  - NETHERITE_HOE
  - NETHERITE_INGOT
  - NETHERITE_LEGGINGS
  - NETHERITE_PICKAXE
  - NETHERITE_SCRAP
  - NETHERITE_SHOVEL
  - NETHERITE_SWORD
  - NETHERRACK
  - NOTE_BLOCK
  - OAK_BOAT
  - OAK_CHEST_BOAT
  - OAK_DOOR
  - OAK_FENCE
  - OAK_FENCE_GATE
  - OAK_LEAVES
  - OAK_LOG
  - OAK_PLANKS
  - OAK_PRESSURE_PLATE
  - OAK_SLAB
  - OAK_STAIRS
  - OAK_TRAPDOOR
  - OAK_WOOD
  - OBSERVER
  - OBSIDIAN
  - OCELOT_SPAWN_EGG
  - OCHRE_FROGLIGHT
  - ORANGE_BED
  - ORANGE_CONCRETE
  - ORANGE_CONCRETE_POWDER
  - ORANGE_GLAZED_TERRACOTTA
  - ORANGE_STAINED_GLASS
  - ORANGE_TERRACOTTA
  - ORANGE_WOOL
  - OXEYE_DAISY
  - OXIDIZED_COPPER
  - OXIDIZED_CUT_COPPER
  - OXIDIZED_CUT_COPPER_SLAB
  - OXIDIZED_CUT_COPPER_STAIRS
  - PACKED_ICE
  - PACKED_MUD
  - PAINTING
  - PANDA_SPAWN_EGG
  - PAPER
  - PARROT_SPAWN_EGG
  - PEARLESCENT_FROGLIGHT
  - PETRIFIED_OAK_SLAB
  - PHANTOM_MEMBRANE
  - PHANTOM_SPAWN_EGG
  - PIG_SPAWN_EGG
  - PIGLIN_BRUTE_SPAWN_EGG
  - PIGLIN_SPAWN_EGG
  - PILLAGER_SPAWN_EGG
  - PINK_BED
  - PINK_CONCRETE
  - PINK_GLAZED_TERRACOTTA
  - PINK_STAINED_GLASS
  - PINK_TERRACOTTA
  - PINK_TULIP
  - PINK_WOOL
  - PISTON
  - PODZOL
  - POINTED_DRIPSTONE
  - POLAR_BEAR_SPAWN_EGG
  - POLISHED_ANDESITE
  - POLISHED_ANDESITE_SLAB
  - POLISHED_ANDESITE_STAIRS
  - POLISHED_BASALT
  - POLISHED_BLACKSTONE
  - POLISHED_BLACKSTONE_BRICK_SLAB
  - POLISHED_BLACKSTONE_BRICK_STAIRS
  - POLISHED_BLACKSTONE_BRICK_WALL
  - POLISHED_BLACKSTONE_BRICKS
  - POLISHED_BLACKSTONE_SLAB
  - POLISHED_BLACKSTONE_STAIRS
  - POLISHED_BLACKSTONE_WALL
  - POLISHED_DEEPSLATE
  - POLISHED_DEEPSLATE_SLAB
  - POLISHED_DEEPSLATE_STAIRS
  - POLISHED_DEEPSLATE_WALL
  - POLISHED_DIORITE
  - POLISHED_DIORITE_SLAB
  - POLISHED_DIORITE_STAIRS
  - POLISHED_GRANITE
  - POLISHED_GRANITE_SLAB
  - POLISHED_GRANITE_STAIRS
  - POPPED_CHORUS_FRUIT
#  - POTATO
#  - POTATOES
  - POTION
  - POWERED_RAIL
  - PRISMARINE
  - PRISMARINE_BRICK_SLAB
  - PRISMARINE_BRICK_STAIRS
  - PRISMARINE_BRICKS
  - PRISMARINE_CRYSTALS
  - PRISMARINE_SHARD
  - PRISMARINE_SLAB
  - PRISMARINE_STAIRS
  - PRISMARINE_WALL
  - PUFFERFISH
  - PUFFERFISH_BUCKET
  - PUFFERFISH_SPAWN_EGG
  - PUMPKIN
  - PUMPKIN_PIE
  - PUMPKIN_STEM
  - PURPLE_BED
  - PURPLE_CONCRETE
  - PURPLE_GLAZED_TERRACOTTA
  - PURPLE_STAINED_GLASS
  - PURPLE_TERRACOTTA
  - PURPLE_WOOL
  - PURPUR_BLOCK
  - PURPUR_PILLAR
  - PURPUR_SLAB
  - PURPUR_STAIRS
  - QUARTZ
  - QUARTZ_BLOCK
  - QUARTZ_BRICKS
  - QUARTZ_PILLAR
  - QUARTZ_SLAB
  - QUARTZ_STAIRS
  - RABBIT_FOOT
  - RABBIT_HIDE
  - RABBIT_SPAWN_EGG
  - RABBIT_STEW
  - RAIL
  - RAVAGER_SPAWN_EGG
  - RAW_COPPER_BLOCK
  - RAW_GOLD
  - RAW_GOLD_BLOCK
  - RAW_IRON
  - RAW_IRON_BLOCK
  - RED_BED
  - RED_CONCRETE
  - RED_CONCRETE_POWDER
  - RED_DYE
  - RED_GLAZED_TERRACOTTA
  - RED_MUSHROOM
  - RED_MUSHROOM_BLOCK
  - RED_NETHER_BRICK_SLAB
  - RED_NETHER_BRICK_STAIRS
  - RED_NETHER_BRICK_WALL
  - RED_NETHER_BRICKS
  - RED_SAND
  - RED_SANDSTONE
  - RED_SANDSTONE_SLAB
  - RED_SANDSTONE_STAIRS
  - RED_SANDSTONE_WALL
  - RED_STAINED_GLASS
  - RED_TERRACOTTA
  - RED_TULIP
  - RED_WOOL
  - REDSTONE
  - REDSTONE_BLOCK
  - REDSTONE_LAMP
  - REDSTONE_ORE
  - REDSTONE_TORCH
  - REDSTONE_WALL_TORCH
  - REDSTONE_WIRE
  - REINFORCED_DEEPSLATE
  - RESPAWN_ANCHOR
  - ROOTED_DIRT
  - ROSE_BUSH
#  - ROTTEN_FLESH
  - SADDLE
  - SALMON
  - SALMON_BUCKET
  - SALMON_SPAWN_EGG
  - SAND
  - SANDSTONE
  - SANDSTONE_SLAB
  - SANDSTONE_STAIRS
  - SANDSTONE_WALL
  - SCAFFOLDING
  - SCULK_CATALYST
  - SCULK_SENSOR
  - SCULK_SHRIEKER
  - SCULK_VEIN
  - SCUTE
  - SEA_LANTERN
  - SHEARS
  - SHEEP_SPAWN_EGG
  - SHIELD
  - SHROOMLIGHT
  - SHULKER_BOX
  - SHULKER_SHELL
  - SHULKER_SPAWN_EGG
  - SILVERFISH_SPAWN_EGG
  - SKELETON_HORSE_SPAWN_EGG
  - SKELETON_SKULL
  - SKELETON_SPAWN_EGG
  - SKELETON_WALL_SKULL
  - SLIME_BALL
  - SLIME_BLOCK
  - SLIME_SPAWN_EGG
  - SMITHING_TABLE
  - SMOKER
  - SMOOTH_BASALT
  - SMOOTH_QUARTZ_SLAB
  - SMOOTH_QUARTZ_STAIRS
  - SMOOTH_RED_SANDSTONE
  - SMOOTH_RED_SANDSTONE_SLAB
  - SMOOTH_RED_SANDSTONE_STAIRS
  - SMOOTH_SANDSTONE
  - SMOOTH_SANDSTONE_SLAB
  - SMOOTH_SANDSTONE_STAIRS
  - SMOOTH_STONE
  - SMOOTH_STONE_SLAB
  - SNOW
  - SNOW_BLOCK
  - SNOWBALL
  - SOUL_CAMPFIRE
  - SOUL_FIRE
  - SOUL_LANTERN
  - SOUL_SAND
  - SOUL_SOIL
  - SOUL_TORCH
  - SOUL_WALL_TORCH
  - SPAWNER
  - SPECTRAL_ARROW
  - SPIDER_EYE
  - SPIDER_SPAWN_EGG
  - SPLASH_POTION
  - SPONGE
  - SPRUCE_BOAT
  - SPRUCE_CHEST_BOAT
  - SPRUCE_DOOR
  - SPRUCE_FENCE
  - SPRUCE_FENCE_GATE
  - SPRUCE_LEAVES
  - SPRUCE_LOG
  - SPRUCE_PLANKS
  - SPRUCE_PRESSURE_PLATE
  - SPRUCE_SLAB
  - SPRUCE_STAIRS
  - SPRUCE_TRAPDOOR
  - SPRUCE_WOOD
  - SPYGLASS
  - SQUID_SPAWN_EGG
  - STICK
  - STICKY_PISTON
  - STONE
  - STONE_AXE
  - STONE_BRICK_SLAB
  - STONE_BRICK_STAIRS
  - STONE_BRICK_WALL
  - STONE_BRICKS
  - STONE_PICKAXE
  - STONE_PRESSURE_PLATE
  - STONE_SHOVEL
  - STONE_SLAB
  - STONE_STAIRS
  - STONE_SWORD
  - STONECUTTER
  - STRAY_SPAWN_EGG
  - STRIDER_SPAWN_EGG
  - STRING
  - STRIPPED_ACACIA_LOG
  - STRIPPED_ACACIA_WOOD
  - STRIPPED_BIRCH_LOG
  - STRIPPED_BIRCH_WOOD
  - STRIPPED_CRIMSON_STEM
  - STRIPPED_DARK_OAK_LOG
  - STRIPPED_DARK_OAK_WOOD
  - STRIPPED_JUNGLE_LOG
  - STRIPPED_JUNGLE_WOOD
  - STRIPPED_MANGROVE_LOG
  - STRIPPED_MANGROVE_WOOD
  - STRIPPED_OAK_LOG
  - STRIPPED_OAK_WOOD
  - STRIPPED_SPRUCE_LOG
  - STRIPPED_SPRUCE_WOOD
  - STRIPPED_WARPED_HYPHAE
  - STRIPPED_WARPED_STEM
  - SUGAR
  - SUGAR_CANE
  - SUSPICIOUS_STEW
#  - SWEET_BERRIES
  - SWEET_BERRY_BUSH
  - TADPOLE_BUCKET
  - TADPOLE_SPAWN_EGG
  - TARGET
  - TERRACOTTA
  - TINTED_GLASS
  - TIPPED_ARROW
  - TNT
  - TORCH
  - TRADER_LLAMA_SPAWN_EGG
  - TRAPPED_CHEST
  - TRIDENT
  - TRIPWIRE
  - TRIPWIRE_HOOK
  - TROPICAL_FISH
  - TROPICAL_FISH_BUCKET
  - TROPICAL_FISH_SPAWN_EGG
  - TUBE_CORAL_BLOCK
  - TUFF
  - TURTLE_EGG
  - TURTLE_HELMET
  - TURTLE_SPAWN_EGG
  - VERDANT_FROGLIGHT
  - VEX_SPAWN_EGG
  - VILLAGER_SPAWN_EGG
  - VINDICATOR_SPAWN_EGG
  - VINE
  - VOID_AIR
  - WALL_TORCH
  - WANDERING_TRADER_SPAWN_EGG
  - WARDEN_SPAWN_EGG
  - WARPED_DOOR
  - WARPED_FENCE
  - WARPED_FENCE_GATE
  - WARPED_FUNGUS
  - WARPED_FUNGUS_ON_A_STICK
  - WARPED_HYPHAE
  - WARPED_NYLIUM
  - WARPED_PLANKS
  - WARPED_PRESSURE_PLATE
  - WARPED_ROOTS
  - WARPED_SLAB
  - WARPED_STAIRS
  - WARPED_STEM
  - WARPED_TRAPDOOR
  - WARPED_WART_BLOCK
  - WATER_BUCKET
  - WATER_CAULDRON
  - WET_SPONGE
  - WHITE_BED
  - WHITE_CONCRETE
  - WHITE_CONCRETE_POWDER
  - WHITE_GLAZED_TERRACOTTA
  - WHITE_STAINED_GLASS
  - WHITE_TERRACOTTA
  - WHITE_WOOL
  - WITCH_SPAWN_EGG
  - WITHER_ROSE
  - WITHER_SKELETON_SKULL
  - WITHER_SKELETON_SPAWN_EGG
  - WITHER_SKELETON_WALL_SKULL
  - WOLF_SPAWN_EGG
  - WOODEN_AXE
  - WOODEN_HOE
  - WOODEN_PICKAXE
  - WOODEN_SHOVEL
  - WOODEN_SWORD
  - WRITABLE_BOOK
  - YELLOW_BED
  - YELLOW_CONCRETE
  - YELLOW_GLAZED_TERRACOTTA
  - YELLOW_STAINED_GLASS
  - YELLOW_TERRACOTTA
  - YELLOW_WOOL
  - ZOGLIN_SPAWN_EGG
  - ZOMBIE_HORSE_SPAWN_EGG
  - ZOMBIE_SPAWN_EGG
  - ZOMBIE_VILLAGER_SPAWN_EGG
  - ZOMBIFIED_PIGLIN_SPAWN_EGG
  - ZOMBIFIED_PIGLIN_SPAWN_EGG